---
# tasks file for haproxy
- name: deploy haproxy
  hosts: frontends
  gather_facts: true
  become: true

- name: Installing configure httpie and haproxy and restart if changed
  block:
    - yum:
        name: "{{ item }}"
        state: latest
      with_item:
       - httpie
       - haproxy
      notify: Restart and enabled haproxy
- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

